# Generated by Django 4.2.16 on 2024-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
