# Generated by Django 4.2.13 on 2024-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publiched',
            field=models.BooleanField(null=True),
        ),
    ]
