# Generated by Django 4.2.13 on 2024-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('basic', 'Basic'), ('family', 'Family'), ('premium', 'Premium')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=50)),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
    ]
