# Generated by Django 4.2.13 on 2024-07-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_work', '0002_audio_name_screenshots_name_videos_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
