# Generated by Django 4.2.13 on 2024-05-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
