# Generated by Django 4.2.13 on 2024-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
